filebeat.inputs:
- type: log
  paths:
    - /var/logs/nginx/*.log
  tags: ["nginx", "json"]
  json.keys_under_root: true
  json.add_error_key: true
- type: log
  paths:
    - /var/logs/mysql/*.log
  tags: ["mysql"]
- type: log
  paths:
    - /var/logs/php/*.log
  tags: ["php"]
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
setup.kibana:
  host: "http://kibana:5601"