---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme
xpack.encryptedSavedObjects:
  encryptionKey: "5fdb0bbe54304ee6a2fd9dff25f9b508"

xpack.actions.preconfigured:
  my-slack1:
    actionTypeId: .slack
    name: 'Slack #xyz'
    secrets:
      webhookUrl: 'https://hooks.slack.com/services/abcd/efgh/ijklmnopqrstuvwxyz'
  webhook-service:
    actionTypeId: .webhook
    name: 'Email service'
    config:
      url: 'https://email-alert-service.elastic.co'
      method: post
      headers:
        header1: value1
        header2: value2
    secrets:
      user: elastic
      password: changeme