version: '3.2'

services:
  uptime:
    container_name: uptime
    build:
      context: extensions/uptime/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./extensions/uptime/config/uptime-server.yml
        target: /usr/share/heartbeat/heartbeat.yml
        read_only: true
    command: heartbeat -e -strict.perms=false
    ports:
      - '9999:9999'
    networks:
      - elk
    depends_on:
      - elasticsearch
